# tf/firebase.tf

# ==============================================================================
# FIREBASE PROJECT SERVICES
# ==============================================================================

# Enable Firebase Management API dynamically
resource "google_project_service" "firebase" {
  project            = var.gcp_project_id
  service            = "firebase.googleapis.com"
  disable_on_destroy = false
}

# ==============================================================================
# FIREBASE INITIALIZATION
# ==============================================================================

# Links Firebase services to the existing Google Cloud Project
resource "google_firebase_project" "default" {
  provider = google-beta
  project  = var.gcp_project_id

  # Ensures Firebase is not initialized before the API is fully active
  depends_on = [google_project_service.firebase]
}

# ==============================================================================
# PROPAGATION DELAY (90 Seconds Pause)
# ==============================================================================

# Forces Terraform to wait for GCP IAM and service accounts replication
resource "time_sleep" "wait_90_seconds" {
  create_duration = "90s"

  # 👇 Starts ticking strictly AFTER the Firebase project is successfully initialized
  depends_on = [google_firebase_project.default]
}

# ==============================================================================
# FIREBASE APPS
# ==============================================================================

# Creates a Web App within the Firebase project for frontend connection
resource "google_firebase_web_app" "frontend" {
  provider     = google-beta
  project      = var.gcp_project_id
  display_name = "BF Analyzer Frontend"

  # CRITICAL: Wait for the 90-second sleep to finish before initiating app setup
  depends_on = [time_sleep.wait_90_seconds]
}

# ==============================================================================
# DATA SOURCES FOR FRONTEND CONFIGURATION
# ==============================================================================

# Automatically fetches configuration details (keys, domains) generated by GCP
data "google_firebase_web_app_config" "frontend_config" {
  provider   = google-beta
  project    = var.gcp_project_id
  web_app_id = google_firebase_web_app.frontend.app_id
}
